<a href="https://colab.research.google.com/github/hvtlou-ui/PREDICTION-MODEL/blob/main/Stock_price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PREDICTION OF STOCK PRICES BY USING MACHINE LEARNING MODELS

IMPORT ALL NECESSARY LIBRARIES

In [ ]:
import quandl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
import sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR

UPLOAD THE DATASET

In [ ]:
df = yf.download('META', start='2020-01-01', end='2025-12-31')

[*********************100%***********************]  1 of 1 completed

UNDERSTANDING THE DATASET

DATASET HEAD

In [ ]:
df.head()

Price            Close        High         Low        Open    Volume
Ticker            META        META        META        META      META
Date
2020-01-02  207.789871  207.799771  204.313175  204.788617  12077100
2020-01-03  206.690369  208.403952  204.986685  205.244228  11188400
2020-01-06  210.583099  210.761384  204.560778  204.739063  17058900
2020-01-07  211.038727  212.544311  209.741157  210.801013  14912400
2020-01-08  213.178253  214.188581  210.593013  210.979313  13475000

DATASET TAIL

In [ ]:
df.tail()

Price            Close        High         Low        Open   Volume
Ticker            META        META        META        META     META
Date
2025-12-23  663.232544  664.289820  656.559720  658.355086  8486800
2025-12-24  665.835876  666.464264  660.499638  660.828808  5627500
2025-12-26  661.586792  667.232292  659.621880  666.344563  7133800
2025-12-29  656.998657  658.554649  652.709711  656.320411  8506500
2025-12-30  664.239990  670.493849  656.150830  656.998623  9187500

DATASET SHAPE

In [ ]:
df.shape

(1507, 5)

ADJUSTED CLOSE PRICE

In [ ]:
df = df[['Close']]
df.head()

Price            Close
Ticker            META
Date
2020-01-02  207.789871
2020-01-03  206.690369
2020-01-06  210.583099
2020-01-07  211.038727
2020-01-08  213.178253

VARIABLE FOR PREDICTION FUTURE PRICE

In [ ]:
forecast_out = 30
df['Prediction'] = df[['Close']].shift(-forecast_out)

#THE INDEPENDENT DATASET
CONVERT THE DATAFRAME TO A NUMPY ARRAY

In [ ]:
X = np.array(df.drop(['Prediction'], axis=1))
X = X[:-forecast_out]

#THE DEPENDENT DATASET
CONVERT THE DATAFRAME TO A NUMPY ARRAY

In [ ]:
y = np.array(df['Prediction'])
y = y[:-forecast_out]

SPLIT THE DATASET

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

TRAIN THE SUPPORT VECTOR MACHINE (REGRESSOR)

In [ ]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, gamma=0.1)

TEST THE MODEL

In [ ]:
svm_confidence = svr_rbf.score(x_test, y_test)
print("svm confidence: ", svm_confidence)

svm confidence:  0.8995634751574356

TRAIN THE LINEAR REGRESSION

In [ ]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

TEST THE MODEL

In [ ]:
lr_confidence = lr.score(x_test, y_test)
print("lr confidence: ", lr_confidence)

lr confidence:  0.9242062200032228

SET x_FORECAST EQUAL TO THE LAST 30RAWS OF THE ORIGINAL DATASET

In [ ]:
x_forecast = np.array(df.drop(['Prediction'], axis=1))[-forecast_out:]

THE LINEAR REGRESSION PREDICTIONS MODEL FOR THE NEXT 'n' DAYS

In [ ]:
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

[605.56215495 601.31321351 594.0645764  592.91387287 597.92988976
 616.42017268 639.20866816 636.64169097 650.74557928 643.78208823
 649.90947607 642.53302317 664.10196807 675.796089   669.28507308
 659.60721313 652.88965605 655.42717898 647.08674684 650.83219526
 660.32116251 652.79099334 667.50679523 661.91584821 664.60299151
 667.98908601 670.5582316  666.36494605 661.83706261 668.98330253]

THE SUPPORT VECTOR REGRESSION PREDICTIONS MODEL FOR THE NEXT 'n' DAYS

In [ ]:
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[577.66441173 711.35589859 592.46484703 561.13061343 661.52021194
 635.70562294 687.41034665 694.88627212 664.95140003 739.6254828
 689.40896358 714.20198783 642.4138794  630.34109539 604.8208662
 522.50848626 532.07560856 507.84715294 716.62307565 661.18045284
 560.270726   537.98445339 744.70946708 647.61676319 646.99359391
 726.53205302 470.36181031 723.71414013 645.27175128 639.42474578]